services:
  browser-api:
    container_name: browser-api
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      # Uncomment if your kernel blocks the sandbox:
      - CHROME_EXTRA_ARGS=--no-sandbox
      - RUST_LOG=info
    env_file:
      - .env
    security_opt:
      - seccomp:unconfined
    shm_size: 2gb
